"""empty message

Revision ID: 035dd06c03c6
Revises: 194ce852c49f
Create Date: 2023-12-20 16:06:26.176215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035dd06c03c6'
down_revision = '194ce852c49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name=op.f('fk_answer_voter_answer_id_answer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_answer_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answer_id', name=op.f('pk_answer_voter'))
    )
    op.drop_table('answer_vote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_vote',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='fk_answer_vote_answer_id_answer', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_answer_vote_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answer_id', name='pk_answer_vote')
    )
    op.drop_table('answer_voter')
    # ### end Alembic commands ###
